# Generated by Django 4.2 on 2023-04-14 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_profile_name_review_date_trip_date_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='user.profile'),
        ),
    ]
