# Generated by Django 4.2 on 2023-04-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_review_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_published',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='trips_as_passenger', to='user.profile'),
        ),
    ]
