# Generated by Django 4.2 on 2023-04-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_trip_date_published_alter_trip_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='placeholder', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='placeholder', max_length=50),
            preserve_default=False,
        ),
    ]
