# Generated by Django 4.2 on 2023-04-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_trip_on_going'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='departure_coordinates',
            field=models.JSONField(default={'latitude': 37.785834, 'latitudeDelta': 0.0922, 'longitude': -122.406417, 'longitudeDelta': 0.05183658170914543}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_coordinates',
            field=models.JSONField(default={'latitude': 37.785834, 'latitudeDelta': 0.0922, 'longitude': -122.406417, 'longitudeDelta': 0.05183658170914543}),
            preserve_default=False,
        ),
    ]
