# Generated by Django 4.2 on 2023-05-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_trip_is_hidden_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='terminated_passengers',
            field=models.ManyToManyField(blank=True, related_name='terminated_trips_as_passenger', to='user.profile'),
        ),
    ]
